# Generated by Django 4.2.1 on 2023-05-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbuddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelbuddy',
            name='img',
            field=models.CharField(max_length=1000),
        ),
    ]
